### ISSUE TITLE
Weekend Checklist

### ISSUE THREAD

**Issue by laanna-grace** [stellasylee/Music-Wordcloud-r-Shiny-app#1]
- [x] E-mail from Prof. Miller
- [x] Make function to tokenize lyrics column for worldcloud
- [x] Data Cleaning/Wrangling (LaAnna)
- [x] Design UI (Stella)
- [x] Experiment with wordcloud customization
- [x] Meet Sunday night
